// SPDX-FileCopyrightText: Vernum Projecten B.V.
// SPDX-License-Identifier: BUSL-1.1

//! Integration tests through the library run path the binary shares.

mod admission;
mod aggregate;
mod ask_all;
mod base_url;
mod completeness;
mod config;
mod contribution_write;
mod credentials;
mod declared;
mod dedup;
mod dedup_write;
mod definition;
mod demographic;
mod directive;
mod distinct;
mod e2e;
mod ehr_by_subject;
mod ehr_id_collision;
mod ehr_scope;
mod endpoint_attributes;
mod endpoint_report;
mod errors;
mod facade;
mod follow_up;
mod healthcheck;
mod http;
mod hygiene;
mod lifecycle;
mod no_destination;
mod options;
mod order;
mod order_key;
mod outbound;
mod outbound_id;
mod path_ehr_id;
mod probed_ehr_id;
mod provenance;
mod query_get;
mod readiness;
mod registry_fhir;
mod reload;
mod request_log;
mod resolution;
mod routing;
mod routing_log;
mod run;
mod shutdown;
mod stored;
mod support;
mod targeting;
mod telemetry;
mod timeouts;
mod track10;
mod versioned_write;
