#!/usr/bin/env bash
# SPDX-FileCopyrightText: Vernum Projecten B.V.
# SPDX-License-Identifier: BUSL-1.1
# File-length guard: a hand-written Rust file is at most $HARD lines, and a
# file over $SOFT lines is split into a module folder before it grows further.
# A Markdown page of the book under website/book/src/ is held to the same
# limits and the same allow-list, and splits into pages of its chapter.
#
# Generated files (a `@generated` banner on the first line) and vendored trees
# are outside the rule. A file listed in scripts/checks/file-length-allow.txt
# is a known breach with the issue that splits it: it passes while it does not
# grow past the line count recorded beside it (the ratchet), and its entry is
# removed by the split. A file over $SOFT and under $HARD that is not listed
# is reported as a warning, never a failure.
#
# Usage:
#   scripts/checks/file-length.sh            check every tracked .rs file and
#                                            every tracked book page
#   scripts/checks/file-length.sh --files F…  check the named files
#   scripts/checks/file-length.sh --record    rewrite the allow-list from the
#                                            current breaches (a split removes
#                                            entries; --record never adds a
#                                            new one without an issue number
#                                            given as --issue N)
#   scripts/checks/file-length.sh --self-test prove each refusal and each pass
#                                            against fixture repositories
#   --root DIR                               check the git tree at DIR instead
#                                            of this repository (the self-test)
# Exit 1 on a hard breach or a listed file that grew; 0 otherwise.
set -euo pipefail
self="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
root="$(dirname "$0")/../.."

SOFT=750
HARD=1000
ALLOW=scripts/checks/file-length-allow.txt

note() { printf '  %s\n' "$*"; }

# The self-test builds one fixture repository per case in a temporary
# directory and runs this guard over it: a Rust file and a book page over the
# limit fail, a listed page passes until it grows, and the near misses pass.
self_test() {
  local work failed=0 n=0
  work="$(mktemp -d)"
  # shellcheck disable=SC2064 # expand $work now: the local is gone at EXIT.
  trap "rm -rf '$work'" EXIT
  # fixture DIR PATH LINES [FIRST]: a tracked file of LINES lines at PATH.
  fixture() {
    local dir="$1" path="$2" count="$3" first="${4:-}"
    mkdir -p "$(dirname "$dir/$path")"
    {
      if [[ -n "$first" ]]; then
        printf '%s\n' "$first"
        count=$((count - 1))
      fi
      seq 1 "$count"
    } > "$dir/$path"
    git -C "$dir" add -- "$path"
  }
  # case_dir: a fresh git repository for one case, named in $d.
  case_dir() {
    n=$((n + 1))
    mkdir -p "$work/$n"
    git -C "$work/$n" init -q
    d="$work/$n"
  }
  # expect WANT NAME DIR: the guard over DIR exits WANT.
  expect() {
    local want="$1" name="$2" dir="$3" status=0
    bash "$self" --root "$dir" > /dev/null 2>&1 || status=$?
    if [[ "$status" -ne "$want" ]]; then
      echo "file-length: self-test failed: $name exited $status, wanted $want." >&2
      failed=1
    fi
  }
  # allow DIR LINES PATH: an allow-list entry for PATH at LINES.
  allow() {
    local dir="$1" lines="$2" path="$3"
    mkdir -p "$dir/scripts/checks"
    printf '%s %s #1\n' "$lines" "$path" > "$dir/$ALLOW"
  }
  local d
  case_dir; fixture "$d" crates/a/src/big.rs $((HARD + 1))
  expect 1 "a Rust file over $HARD lines" "$d"
  case_dir; fixture "$d" website/book/src/operate/big.md $((HARD + 1))
  expect 1 "a book page over $HARD lines" "$d"
  case_dir; fixture "$d" website/book/src/big.md $((HARD + 1))
  allow "$d" $((HARD + 1)) website/book/src/big.md
  expect 0 "a listed book page at its recorded count" "$d"
  case_dir; fixture "$d" crates/a/src/small.rs 10
  allow "$d" $((HARD + 1)) crates/a/src/gone.rs
  expect 1 "an entry for a file that does not exist" "$d"
  case_dir; fixture "$d" crates/a/src/big.rs $((HARD + 1))
  allow "$d" "$HARD" crates/a/src/big.rs
  expect 1 "a listed Rust file that grew" "$d"
  case_dir; fixture "$d" crates/a/src/big.rs $((HARD + 1))
  allow "$d" 'HARD+1' crates/a/src/big.rs
  expect 1 "an entry whose count is no number" "$d"
  case_dir; fixture "$d" crates/a/src/big.rs "$SOFT"
  allow "$d" $((HARD + 1)) crates/a/src/big.rs
  expect 1 "a listed Rust file back under $SOFT" "$d"
  case_dir
  fixture "$d" website/book/src/long.md $((SOFT + 1))
  fixture "$d" crates/a/src/long.rs $((SOFT + 1))
  fixture "$d" docs/big.md $((HARD + 1))
  fixture "$d" crates/a/vendor/big.rs $((HARD + 1))
  fixture "$d" crates/a/src/gen.rs $((HARD + 1)) '// @generated by a fixture'
  expect 0 "the near misses (over $SOFT only, outside the book, vendored, generated)" "$d"
  if [[ "$failed" -ne 0 ]]; then
    exit 1
  fi
  echo "file-length: self-test OK."
}

mode=check
issue=""
files=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --files) mode=files; shift; while [[ $# -gt 0 ]] && [[ "${1#--}" = "$1" ]]; do files+=("$1"); shift; done ;;
    --record) mode=record; shift ;;
    --issue) issue="$2"; shift 2 ;;
    --root) root="$2"; shift 2 ;;
    --self-test) self_test; exit 0 ;;
    *) printf 'file-length: unknown argument %s\n' "$1" >&2; exit 2 ;;
  esac
done
cd "$root"

if [[ "$mode" != "files" ]]; then
  while IFS= read -r f; do files+=("$f"); done < <(git ls-files -- '*.rs' 'website/book/src/*.md' ':(glob,exclude)**/vendor/**')
fi

# A template under a generator's src/templates/ is the text of one generated
# file, embedded verbatim, so it is generated output in source form.
hand_written() {
  local file="$1"
  case "$file" in
  */vendor/* | */src/templates/*) return 1 ;;
  *) ;;
  esac
  ! head -n1 "$file" | grep -q '@generated'
}

# How a file over the limit splits: a Rust file into a module folder, a book
# page into pages of its chapter.
split_hint() {
  case "$1" in
  *.md) printf 'pages of its chapter in SUMMARY.md' ;;
  *) printf 'a module folder' ;;
  esac
}

# The allow-list entry of a path, as "<lines> <tag>", or nothing (bash 3.2 has
# no associative arrays, so the list is read per lookup).
listed() {
  local path="$1"
  [[ -f "$ALLOW" ]] || return 0
  awk -v p="$path" '$1 !~ /^#/ && $2 == p { print $1, $3 }' "$ALLOW"
}

fail=0
warn=0
breaches=()
# A listed path that no longer exists is a stale entry: the split removed the
# file, so the entry goes with it.
if [[ "$mode" = "check" ]] && [[ -f "$ALLOW" ]]; then
  while IFS=' ' read -r first path _; do
    case "$first" in
    '' | \#*) continue ;;
    *) ;;
    esac
    [[ -f "$path" ]] && continue
    note "FAIL $path is listed but does not exist; remove its allow-list entry"
    fail=1
  done < "$ALLOW"
fi
for f in ${files[@]+"${files[@]}"}; do
  [[ -f "$f" ]] || continue
  hand_written "$f" || continue
  n=$(wc -l < "$f" | tr -d " ")
  if [[ "$n" -gt "$SOFT" ]]; then
    breaches+=("$n $f")
  fi
  entry=$(listed "$f")
  if [[ -n "$entry" ]]; then
    recorded=${entry%% *}
    tag=${entry#* }
    # [[ -gt ]] evaluates its operands as arithmetic, so the count read from
    # the allow-list is held to digits before it is compared.
    if [[ ! "$recorded" =~ ^[0-9]+$ ]]; then
      note "FAIL $f: its allow-list entry records '$recorded', not a line count"
      fail=1
    elif [[ "$n" -gt "$recorded" ]]; then
      note "FAIL $f: $n lines, listed at $recorded ($tag); a listed file may not grow, split it"
      fail=1
    elif [[ "$n" -le "$SOFT" ]]; then
      note "FAIL $f: $n lines, under the limit; remove its allow-list entry"
      fail=1
    fi
    continue
  fi
  if [[ "$n" -gt "$HARD" ]]; then
    note "FAIL $f: $n lines, over the hard limit of $HARD; split it into $(split_hint "$f")"
    fail=1
  elif [[ "$n" -gt "$SOFT" ]]; then
    note "warn $f: $n lines, over $SOFT; split it before it grows"
    warn=$((warn + 1))
  fi
done

if [[ "$mode" = "record" ]]; then
  {
    printf '# Known file-length breaches: "<lines> <path> #<issue>". A listed file passes\n'
    printf '# while it does not grow past its recorded count; the split removes the entry.\n'
    for b in ${breaches[@]+"${breaches[@]}"}; do
      n=${b%% *}; p=${b#* }
      entry=$(listed "$p")
      if [[ -n "$entry" ]]; then
        printf '%s %s %s\n' "$n" "$p" "${entry#* }"
      elif [[ -n "$issue" ]]; then
        printf '%s %s #%s\n' "$n" "$p" "$issue"
      else
        printf 'file-length: %s is a new breach; pass --issue N to record it\n' "$p" >&2
        exit 2
      fi
    done | sort -k2
  } > "$ALLOW.tmp" && mv "$ALLOW.tmp" "$ALLOW"
  note "recorded ${#breaches[@]} breaches in $ALLOW"
  exit 0
fi

if [[ "$fail" -eq 0 ]]; then
  note "OK: no hand-written .rs file or book page over $HARD lines outside the allow-list ($warn over $SOFT unlisted)"
fi
exit "$fail"
